Implement `into_inner`, and simplified `unsafe` usage
terrarier2111/owned-drop pull request #1
Opened 2024-02-21 01:31 UTC by dewert99

I implemented an `into_inner` method for `DropOwned` to convert it into its inner data, and simplified the `drop` implementation. I added tests for both and checked them with `miri` to help check them for soundness.

2024-02-22 20:27 UTC, terrarier2111 commented
Thank you very much for your work, i greatly appreciate it :)

2024-02-22 20:28 UTC, terrarier2111 requested changes

2024-02-22 20:28 UTC, terrarier2111 commented on src/lib.rs
> +        // SAFETY the inner `ManuallyDrop` will never get used again since put it in the outer
i think there's a "we" missing after "since"

2024-02-22 20:28 UTC, terrarier2111 commented on src/lib.rs
> +        // `ManuallyDrop` which will cause use to forget it
here the "use" should be an "us"

2024-02-23 17:49 UTC, dewert99 commented
Thanks, I made the fixes

2024-02-25 10:40 UTC, terrarier2111 commented
This looks great, thank you :)

2024-02-25 10:40 UTC, merged